CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`password` VARCHAR(255) NULL DEFAULT NULL,
	`is_active` TINYINT(1) NULL DEFAULT NULL,
	`app_id` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)